const {_electron:electron}=require('playwright'),http=require('node:http'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
(async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'shiban-integration-'));let requests=[];const server=http.createServer(async(req,res)=>{let chunks=[];for await(const c of req)chunks.push(c);const body=Buffer.concat(chunks);requests.push({url:req.url,body});res.setHeader('content-type','application/json');if(req.url==='/v1/audio/transcriptions'){res.end(JSON.stringify({text:'帮我记录完成：整理图表'}));return;}
const input=JSON.parse(body);const last=input.messages.at(-1);if(input.tools){res.end(JSON.stringify({choices:[{message:last.role==='tool'?{role:'assistant',content:'已记入完成日志。'}:{role:'assistant',content:null,tool_calls:[{id:'fixture-call',type:'function',function:{name:'manage_record',arguments:JSON.stringify({kind:'log',op:'add',data:{title:'整理图表'}})}}]}}]}));}else res.end(JSON.stringify({choices:[{message:{role:'assistant',content:JSON.stringify({items:[{title:'完成集成检查',evidence:'所有集成检查通过',completedAt:null}]})}}]}));});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port+'/v1';const env={...process.env,SHIBAN_TEST:'1',SHIBAN_TEST_DIR:dir};delete env.ELECTRON_RUN_AS_NODE;let app;
try{app=await electron.launch({args:[path.join(__dirname,'..'),'--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream'],env});for(let i=0;i<100&&!app.windows().some(w=>w.url().endsWith('index.html'));i++)await new Promise(r=>setTimeout(r,100));const page=app.windows().find(w=>w.url().endsWith('index.html'));await page.waitForSelector('#record');const errors=[];page.on('pageerror',e=>errors.push(e.message));
const result=await page.evaluate(async base=>window.shiban.call('settings',{chat:{baseUrl:base,model:'test-model',key:'mock-secret'},speech:{mode:'cloud',baseUrl:base,model:'test-whisper',key:'mock-speech'}}),base);assert.ok(result.ok);
await page.locator('#record').click();await page.locator('#record.recording').waitFor();await page.waitForTimeout(900);await page.locator('#record').click();await page.waitForFunction(()=>document.querySelector('#chat-input').value.includes('整理图表'));assert.equal((await page.evaluate(()=>window.shiban.call('state'))).value.logs.length,0,'Transcription never auto-executes');await page.locator('#send').click();await page.waitForFunction(async()=>((await window.shiban.call('state')).value.logs.length===1));assert.ok(requests.some(r=>r.url==='/v1/audio/transcriptions'&&r.body.includes(Buffer.from('RIFF'))));const current=(await page.evaluate(()=>window.shiban.call('state'))).value;await page.evaluate(id=>window.shiban.call('undo',id),current.history[0].id);assert.equal((await page.evaluate(()=>window.shiban.call('state'))).value.logs.length,0);
const file=path.join(dir,'session.jsonl');fs.writeFileSync(file,JSON.stringify({message:{role:'assistant',content:[{type:'text',text:'所有集成检查通过，已经完成。'}]}}));await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},file);const added=await page.evaluate(()=>window.shiban.call('source-add','file'));assert.ok(added.ok);const source=(await page.evaluate(()=>window.shiban.call('state'))).value.sources[0];await page.evaluate(id=>window.shiban.call('source-toggle',id),source.id);assert.ok((await page.evaluate(()=>window.shiban.call('source-scan'))).ok);let s=(await page.evaluate(()=>window.shiban.call('state'))).value;assert.equal(s.drafts.length,1);await page.evaluate(id=>window.shiban.call('action',{kind:'draft',op:'accept',id}),s.drafts[0].id);s=(await page.evaluate(()=>window.shiban.call('state'))).value;assert.equal(s.logs.length,1);
const icon=path.resolve(__dirname,'../assets/icon.png');await app.evaluate(({dialog},icon)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[icon]});},icon);assert.ok((await page.evaluate(()=>window.shiban.call('pet-import'))).ok);s=(await page.evaluate(()=>window.shiban.call('state'))).value;assert.equal(s.petData.rows,0);assert.match(s.petData.url,/^data:image\/png/);assert.deepEqual(errors,[]);console.log('PASS: real loopback HTTP, recorded WAV from simulated microphone, editable transcription, AI tool action + undo, selected-source summary + acceptance, pet image import');
}finally{if(app)await app.close();await new Promise(r=>server.close(r));fs.rmSync(dir,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
