const {_electron:electron}=require('playwright'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
(async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'jot-ui-'));const env={...process.env,SHIBAN_TEST:'1',SHIBAN_TEST_DIR:dir};delete env.ELECTRON_RUN_AS_NODE;let app;
try{app=await electron.launch(process.env.SHIBAN_RELEASE?{executablePath:process.env.SHIBAN_RELEASE,args:[],env}:{args:[path.join(__dirname,'..')],env});for(let i=0;i<100&&(!app.windows().some(w=>w.url().endsWith('index.html'))||!app.windows().some(w=>w.url().endsWith('pet.html')));i++)await new Promise(r=>setTimeout(r,100));const page=app.windows().find(w=>w.url().endsWith('index.html')),pet=app.windows().find(w=>w.url().endsWith('pet.html'));const errors=[];page.on('pageerror',e=>errors.push(e.message));pet.on('pageerror',e=>errors.push(e.message));await page.waitForSelector('#send');await pet.locator('#minimal').waitFor({state:'visible'});await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().forEach(w=>{w.showInactive();w.webContents.setBackgroundThrottling(false);}));
assert.equal(await page.title(),'Jot');assert.deepEqual(await page.locator('#nav button').allTextContents(),['Today','Todo 0','DDL 0']);assert.equal(await page.locator('.traffic').count(),3);assert.equal((await page.evaluate(()=>window.shiban.call('state'))).value.settings.motion,false);
await page.locator('#settings-button').click();await page.locator('[name=chatStyle]').selectOption('precise');await page.locator('[name=systemPrompt]').fill('称呼我为同学，回答尽量精简。');await page.locator('[name=chatBase]').fill('https://cxapi.alvin.im/v1');await page.locator('[name=chatModel]').fill('cx/gpt-5.6-luna');await page.locator('#settings-form button[type=submit]').click();await page.waitForFunction(async()=>((await window.shiban.call('state')).value.settings.chat.systemPrompt||'').includes('称呼我'));let s=(await page.evaluate(()=>window.shiban.call('state'))).value;assert.equal(s.settings.chat.style,'precise');assert.equal(s.settings.chat.systemPrompt,'称呼我为同学，回答尽量精简。');
assert.equal((await page.evaluate(()=>window.shiban.call('settings',{chat:{systemPrompt:'x'.repeat(8001)}}))).ok,false);assert.equal((await page.evaluate(()=>window.shiban.call('settings',{chat:{style:'invalid'}}))).ok,false);
await page.locator('#nav [data-page=todo]').click();await page.locator('#add-main').click();await page.locator('[name=title]').fill('高数作业');await page.locator('#edit-form button[type=submit]').click();await page.waitForFunction(async()=>((await window.shiban.call('state')).value.todos.length===1));
await page.evaluate(async()=>{const d=new Date();d.setHours(20,0,0,0);await window.shiban.call('action',{kind:'ddl',op:'add',data:{title:'提交实验报告',dueAt:d.toISOString()}});await window.shiban.call('action',{kind:'todo',op:'add',data:{title:'整理实验图表'}});await window.shiban.call('action',{kind:'log',op:'add',data:{title:'读完一篇论文'}});});
await page.locator('#nav [data-page=today]').click();await page.locator('.today-list .task-row').first().waitFor();assert.equal(await page.locator('.today-list .task-row').count(),3);assert.ok((await page.locator('#completion-count').innerText()).includes('1'));
await page.waitForTimeout(250);await page.evaluate(()=>document.querySelector('#toast').hidden=true);const out=path.resolve(__dirname,'../../../outputs');await page.screenshot({path:path.join(out,'Jot-v0.3-首页.png'),omitBackground:true});await pet.screenshot({path:path.join(out,'Jot-v0.3-极简胶囊.png'),omitBackground:true});
await page.locator('#completion-count').click();await page.locator('.log-item').waitFor();await page.locator('#nav [data-page=ddl]').click();await page.locator('#ddl-sort').selectOption('createdAt-asc');assert.equal(await page.locator('#ddl-sort').inputValue(),'createdAt-asc');await page.screenshot({path:path.join(out,'Jot-v0.3-DDL.png'),omitBackground:true});
await page.locator('#settings-button').click();await page.screenshot({path:path.join(out,'Jot-v0.3-设置.png'),omitBackground:true});
const source=path.join(os.homedir(),'.codex/pets/chestnut/pet.json');if(fs.existsSync(source)){await app.evaluate(({dialog},source)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[source]});},source);await page.locator('#import-pet').click();await pet.locator('canvas').waitFor({state:'visible'});assert.deepEqual(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('pet.html')).getSize()),[132,146]);await page.locator('#minimal-pet').click();await pet.locator('#minimal').waitFor({state:'visible'});assert.deepEqual(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('pet.html')).getSize()),[168,66]);}
await page.locator('#hide').click();await pet.locator('#capsule-jot').click();assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('index.html')).isVisible()),true);
await pet.locator('#capsule-expand').click();assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('index.html')).isVisible()),false);await pet.locator('#capsule-expand').click();await page.locator('#maximize').click();assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('index.html')).isMaximized()),true);await page.locator('#maximize').click();await page.locator('#minimize').click();assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('index.html')).isMinimized()),true);await pet.locator('#capsule-jot').click();
await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('index.html')).setSize(520,580));for(const tab of ['today','todo','ddl']){await page.locator(`#nav [data-page=${tab}]`).click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.equal(await page.locator('#chat-input').isVisible(),true);}assert.deepEqual(errors,[]);console.log('PASS: Jot C layout, colored traffic controls, prompt persistence/validation, CRUD, DDL sort, imported pet/capsule switch, capsule buttons, compact width, no page errors');
}finally{if(app)await app.close();fs.rmSync(dir,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
