const { _electron:electron }=require('playwright');const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
(async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'shiban-ui-')),qa=path.join(__dirname,'../qa');fs.mkdirSync(qa,{recursive:true});const env={...process.env,SHIBAN_TEST:'1',SHIBAN_TEST_DIR:dir};delete env.ELECTRON_RUN_AS_NODE;const app=await electron.launch({args:[path.join(__dirname,'..')],env});let failures=[];try{
  for(let i=0;i<100&&!app.windows().some(w=>w.url().endsWith('index.html'));i++)await new Promise(r=>setTimeout(r,100));
  const windows=app.windows();let page=windows.find(w=>w.url().endsWith('index.html'));if(!page){await new Promise(r=>setTimeout(r,1000));page=app.windows().find(w=>w.url().endsWith('index.html'));}
  assert.ok(page,'Panel exists');page.on('pageerror',e=>failures.push(e.message));await page.waitForSelector('#add-main');await page.locator('#add-main').click();await page.locator('#edit-form input[name=title]').fill('整理实验图表');await page.locator('#edit-form button[type=submit]').click();await page.getByRole('button',{name:'撤销',exact:true}).first().waitFor();assert.equal((await page.evaluate(()=>window.shiban.call('state'))).value.todos.length,1);
  await page.locator('#nav [data-page=ddl]').click();await page.locator('#add-main').click();await page.locator('#edit-form input[name=title]').fill('提交通信实验报告');await page.locator('#edit-form input[name=dueAt]').fill('2026-10-01T17:00');await page.locator('#edit-form button[type=submit]').click();await page.locator('#ddl-sort').selectOption('createdAt-desc');assert.equal(await page.locator('#ddl-sort').inputValue(),'createdAt-desc');
  await page.locator('#nav [data-page=todo]').click();await page.locator('[data-edit]').first().click();const select=page.locator('#edit-form select[name=ddlId]');const option=await select.locator('option').nth(1).getAttribute('value');await select.selectOption(option);await page.locator('#edit-form button[type=submit]').click();await page.locator('[data-complete]').first().click();
  let state=(await page.evaluate(()=>window.shiban.call('state'))).value;assert.equal(state.logs.length,1);assert.equal(state.ddls[0].status,'open');assert.equal(state.stats.today,1);
  await page.locator('#nav [data-page=log]').click();await page.locator('#page-title').filter({hasText:'完成日志'}).waitFor();assert.equal(await page.locator('.log-item').count(),1);
  await page.locator('#add-main').click();await page.locator('#edit-form input[name=title]').fill('<img src=x onerror=alert(1)>');await page.locator('#edit-form button[type=submit]').click();assert.equal(await page.locator('.log-item img').count(),0);
  await page.locator('.sidebar-bottom [data-page=settings]').click();await page.locator('input[name=chatBase]').fill('http://localhost:9999/v1');await page.locator('input[name=chatModel]').fill('mock');await page.locator('input[name=chatKey]').fill('test-secret-do-not-leak');await page.locator('#settings-form button[type=submit]').click();await page.waitForTimeout(500);state=(await page.evaluate(()=>window.shiban.call('state'))).value;assert.equal(state.settings.chat.hasKey,true);assert.equal(state.settings.chat.key,undefined);assert.ok(!fs.readFileSync(path.join(dir,'data.json'),'utf8').includes('test-secret-do-not-leak'));
  await page.screenshot({path:path.join(qa,'settings.png')});await page.locator('#nav [data-page=today]').click();await page.screenshot({path:path.join(qa,'today.png')});await page.locator('#nav [data-page=ddl]').click();await page.screenshot({path:path.join(qa,'ddl.png')});const pet=app.windows().find(w=>w.url().endsWith('pet.html'));await pet.screenshot({path:path.join(qa,'pet.png'),omitBackground:true});assert.deepEqual(failures,[]);
  console.log('PASS: desktop UI CRUD, linking, sorting, completion log, XSS escaping, encrypted settings, screenshots');
}finally{await app.close();fs.rmSync(dir,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
