const {_electron:electron}=require('playwright'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
(async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'shiban-v02-'));const env={...process.env,SHIBAN_TEST:'1',SHIBAN_TEST_DIR:dir};delete env.ELECTRON_RUN_AS_NODE;const app=await electron.launch({args:[path.join(__dirname,'..')],env});try{
for(let i=0;i<100&&(!app.windows().some(w=>w.url().endsWith('index.html'))||!app.windows().some(w=>w.url().endsWith('pet.html')));i++)await new Promise(r=>setTimeout(r,100));const page=app.windows().find(w=>w.url().endsWith('index.html')),pet=app.windows().find(w=>w.url().endsWith('pet.html'));await page.waitForSelector('#page-title');const errors=[];page.on('pageerror',e=>errors.push(e.message));pet.on('pageerror',e=>errors.push(e.message));await app.evaluate(({BrowserWindow})=>{for(const w of BrowserWindow.getAllWindows()){w.webContents.setBackgroundThrottling(false);w.showInactive();}});
assert.deepEqual(await page.locator('#nav [data-page]').evaluateAll(es=>es.map(e=>e.dataset.page)),['today','todo','ddl']);assert.equal(await page.locator('#messages').isVisible(),false);const geometry=await page.evaluate(()=>{const m=document.querySelector('main').getBoundingClientRect(),c=document.querySelector('.chat').getBoundingClientRect();return {below:c.top>=m.bottom-1,fullWidth:c.width===innerWidth,docWidth:document.documentElement.scrollWidth,viewport:innerWidth};});assert.equal(geometry.below,true);assert.equal(geometry.fullWidth,true);assert.equal(geometry.docWidth,geometry.viewport);
await page.locator('#chat-toggle').click();assert.equal(await page.locator('#messages').isVisible(),true);await page.locator('#chat-close').click();assert.equal(await page.locator('#chat-input').isVisible(),true);assert.equal(await page.locator('#messages').isVisible(),false);
await page.locator('#nav [data-page=todo]').click();await page.locator('#add-main').click();await page.locator('input[name=title]').fill('确认新版界面');await page.locator('#edit-form button[type=submit]').click();await page.locator('[data-complete]').first().click();await page.locator('#settings-button').click();await page.locator('.settings-links [data-page=log]').click();await page.locator('.log-item').waitFor();assert.equal(await page.locator('.log-item').count(),1);
await page.locator('#settings-button').click();await page.locator('input[name=chatBase]').fill('https://cxapi.alvin.im/v1');await page.locator('input[name=chatModel]').fill('cx/gpt-5.6-luna');await page.locator('#settings-form button[type=submit]').click();await page.waitForTimeout(150);assert.equal((await page.evaluate(()=>window.shiban.call('state'))).value.settings.chat.model,'cx/gpt-5.6-luna');
const source=path.join(os.homedir(),'.codex/pets/chestnut/spritesheet.webp');if(fs.existsSync(source)){fs.copyFileSync(source,path.join(dir,'custom-skin.webp'));const manifest=path.join(dir,'pet.json');fs.writeFileSync(manifest,JSON.stringify({displayName:'Chestnut',spriteVersionNumber:2,spritesheetPath:'custom-skin.webp'}));await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},manifest);await page.locator('#import-pet').click();await pet.waitForFunction(()=>!document.querySelector('canvas').hidden&&document.querySelector('canvas').getContext('2d').getImageData(0,0,192,208).data.some((v,i)=>i%4===3&&v>0));const s=(await page.evaluate(()=>window.shiban.call('state'))).value;assert.equal(s.petData.rows,11);assert.equal(s.petData.mime,'image/webp');assert.ok(fs.readFileSync(path.join(dir,s.settings.pet.file)).equals(fs.readFileSync(source)));
await page.locator('#minimal-pet').click();await pet.locator('#minimal').waitFor({state:'visible'});assert.equal(await pet.locator('canvas').isVisible(),false);await page.locator('#restore-pet').click();await pet.locator('canvas').waitFor({state:'visible'});
const still=await pet.evaluate(()=>document.querySelector('canvas').toDataURL());await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('pet.html'));w.webContents.send('pet-state','thinking');w.webContents.send('pet-gaze',{x:-150,y:0});});await page.waitForTimeout(300);assert.equal(await pet.evaluate(()=>document.querySelector('canvas').toDataURL()),still,'calm pet stays visually still');
await page.evaluate(()=>window.shiban.call('settings',{motion:true}));await pet.waitForFunction(()=>motion===true);
await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('pet.html'));w.webContents.send('pet-state','idle');w.webContents.send('pet-gaze',{x:-150,y:0});});await pet.waitForFunction(()=>gaze===12);assert.equal(await pet.evaluate(()=>gaze),12);
}
await page.locator('#nav [data-page=today]').click();await page.waitForTimeout(200);const qa=path.resolve(__dirname,'../qa');fs.mkdirSync(qa,{recursive:true});await page.screenshot({path:path.join(qa,'v02-today.png')});await page.locator('#settings-button').click();await page.screenshot({path:path.join(qa,'v02-settings.png')});await pet.screenshot({path:path.join(qa,'v02-pet.png'),omitBackground:true});
await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('index.html')).setSize(760,620));await page.locator('#nav [data-page=today]').click();await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:path.join(qa,'v02-compact.png')});assert.deepEqual(errors,[]);console.log('PASS: three tabs, gear settings, full-width bottom composer, chat collapse, CRUD, logs access, settings save, real WebP spritesheetPath import, byte preservation, skin switching, 16-direction gaze, compact layout');
}finally{await app.close();fs.rmSync(dir,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
