const {_electron:electron}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const http=require('node:http');
(async()=>{
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'jot-v05-ui-'));
  const env={...process.env,SHIBAN_TEST:'1',SHIBAN_TEST_DIR:dir};delete env.ELECTRON_RUN_AS_NODE;
  let app;
  const modelServer=http.createServer((req,res)=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify(req.url?.endsWith('/models')?{data:[{id:'demo-a'},{id:'Jot Demo',display_name:'Jot Demo'}]}:{choices:[{message:{role:'assistant',content:'报告大纲已经完成了。接下来可以先整理会议要点，散步留到晚上。课程项目这个长期 Todo 会继续保留，不会因为今天的一步完成就消失。'}}]}));});
  await new Promise(resolve=>modelServer.listen(0,'127.0.0.1',resolve));
  try{
    app=await electron.launch(process.env.SHIBAN_RELEASE?{executablePath:process.env.SHIBAN_RELEASE,args:[],env}:{args:[path.join(__dirname,'..')],env});
    for(let i=0;i<100&&!app.windows().some(w=>w.url().endsWith('index.html'));i++)await new Promise(r=>setTimeout(r,100));
    const page=app.windows().find(w=>w.url().endsWith('index.html'));
    assert.ok(page,'panel exists');
    const errors=[];page.on('pageerror',e=>errors.push(e.message));
    await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('index.html')).show());
    try{await page.waitForSelector('.jot-section-head',{timeout:5000});}catch(e){console.error('page errors:',errors,'body:',(await page.locator('body').innerText()).slice(0,500));throw e;}
    assert.equal(await page.locator('#nav button:visible').count(),2);
    assert.equal(await page.locator('#messages').isVisible(),false);
    assert.equal(await page.locator('#chat-launcher').isVisible(),true);
    assert.equal((await page.locator('#chat-launcher').innerText()).replace(/\s+/g,' ').trim(),'Jot it! ›');
    const today=await page.evaluate(()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;});
    const todo=await page.evaluate(()=>window.shiban.call('action',{kind:'todo',op:'add',data:{title:'完成课程项目报告',dueAt:new Date(Date.now()+86400000).toISOString()}}));assert.equal(todo.ok,true);
    const add=await page.evaluate(({date,id})=>window.shiban.call('action',{kind:'today',op:'add',data:{title:'把报告大纲列出来',day:date,todoId:id}}),{date:today,id:todo.value?.result?.id});assert.equal(add.ok,true);
    for(const title of ['整理上午会议要点','晚饭后散步'])assert.equal((await page.evaluate(({date,title})=>window.shiban.call('action',{kind:'today',op:'add',data:{title,day:date}}),{date:today,title})).ok,true);
    await page.locator('.jot-task').filter({hasText:'把报告大纲列出来'}).waitFor();
    assert.equal(await page.locator('.jot-task-list .jot-task').first().evaluate(el=>getComputedStyle(el).borderTopStyle),'solid');
    await page.waitForTimeout(400);
    await page.screenshot({path:path.join(__dirname,'../qa/v069-today.png'),animations:'disabled'});
    await page.locator('.jot-task').filter({hasText:'把报告大纲列出来'}).locator('.jot-check').click();
    await page.waitForFunction(async()=>((await window.shiban.call('state')).value.todayActions[0].status==='done'));
    assert.equal((await page.evaluate(()=>window.shiban.call('state'))).value.todos[0].status,'open');
    await page.locator('#nav [data-page=todo]').click();
    await page.locator('[data-filter=all]').click();
    assert.ok((await page.locator('.jot-todo-list').innerText()).includes('完成课程项目报告'));
    await page.locator('#toast').evaluate(el=>el.hidden=true);
    await page.waitForTimeout(400);
    await page.screenshot({path:path.join(__dirname,'../qa/v069-todo.png'),animations:'disabled'});
    await page.locator('.jot-task-edit').click();
    await page.locator('[name=completionNote]').fill('大纲已经确定，下一步补充案例。');await page.locator('#edit-form button[type=submit]').click();
    await page.waitForFunction(async()=>((await window.shiban.call('state')).value.todos[0]?.completionNote==='大纲已经确定，下一步补充案例。'));
    const beforeWidth=await page.evaluate(()=>innerWidth);
    await page.locator('#chat-launcher').click();assert.equal(await page.locator('#messages').isVisible(),true);
    await page.waitForTimeout(250);
    const drawer=await page.locator('.chat').boundingBox();
    assert.ok(drawer.width>=280,'expanded conversation has usable width');
    assert.ok((await page.locator('.chat-head').isVisible()),'drawer header visible');
    if((await page.evaluate(()=>innerWidth))>=900){const mainBounds=await page.locator('main').boundingBox();assert.ok(mainBounds.x+mainBounds.width<=drawer.x+2,'drawer is to the right of the page');}
    await page.locator('#model-label').click();await page.locator('#chat-model-menu').waitFor({state:'visible'});
    assert.ok((await page.locator('#chat-model-menu').innerText()).includes('API 地址'));
    await page.locator('#model-label').click();
    const modelUrl=`http://127.0.0.1:${modelServer.address().port}/v1`;
    assert.equal((await page.evaluate(url=>window.shiban.call('settings',{chat:{baseUrl:url,model:'demo-a',key:''}}),modelUrl)).ok,true);
    await page.locator('#model-label').click();await page.locator('[data-chat-model="Jot Demo"]').waitFor();
    await page.locator('[data-chat-model="Jot Demo"]').click();
    await page.waitForFunction(async()=>(await window.shiban.call('state')).value.settings.chat.model==='Jot Demo');
    await page.locator('#chat-input').fill('今天先做哪件事？');await page.locator('#send').click();
    await page.locator('.message.assistant').waitFor();
    assert.equal(await page.locator('.message.assistant').evaluate(el=>getComputedStyle(el).borderTopStyle),'solid');
    const rendered=await page.evaluate(()=>renderMarkdown('**重点**\n\n- 第一条\n- 第二条\n\n<script>alert(1)</script>'));
    assert.match(rendered,/<strong>重点<\/strong>/);
    assert.match(rendered,/<li>第一条<\/li>/);
    assert.ok(!rendered.includes('<script>'));
    assert.equal(await page.locator('#chat-context-count').isVisible(),true);
    await page.locator('#toast').evaluate(el=>el.hidden=true);
    await page.locator('#nav [data-page=today]').click();
    await page.waitForTimeout(450);
    await page.screenshot({path:path.join(__dirname,'../qa/v069-today-chat.png'),animations:'disabled'});
    await page.locator('#chat-collapse-pill').click();assert.equal(await page.locator('#messages').isVisible(),false);assert.equal(await page.locator('#chat-launcher').isVisible(),true);
    await page.waitForTimeout(350);
    await page.locator('#calendar-button').click();
    await page.locator('.jot-cal-cell').first().waitFor();
    assert.equal(await page.locator('.jot-calendar-legend span').count(),5);
    assert.ok(await page.locator('.jot-cal-item.today.done').count()>=1,'completed Today action has its own calendar color');
    assert.notEqual(await page.locator('.jot-cal-item.today.done').first().evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(236, 236, 239)');
    for(const mode of ['week','day','month']){await page.locator(`[data-cal-mode=${mode}]`).click();assert.ok(await page.locator('.jot-cal-cell').count()>=1);}
    await page.screenshot({path:path.join(__dirname,'../qa/v05-calendar.png')});
    await page.locator('#settings-button').click();
    try{await page.locator('#profile-new').waitFor({timeout:5000});}catch(e){console.error('settings errors:',errors,'body:',(await page.locator('body').innerText()).slice(0,800));throw e;}
    assert.equal(await page.locator('#profile-test-edit').isVisible(),true);
    assert.equal(await page.locator('#settings-form button[type=submit]').count(),0);
    await page.locator('[data-settings-tab=memory]').click();
    assert.equal(await page.locator('[name=memoryStable]').isVisible(),true);
    assert.equal(await page.locator('[name=memoryAuto]').isChecked(),true);
    await page.locator('[name=memoryStable]').fill('偏好简洁中文');
    await page.waitForFunction(async()=>(await window.shiban.call('state')).value.settings.chat.memoryStable==='偏好简洁中文');
    await page.locator('[name=memoryRecent]').fill('最近在整理实验');
    await page.waitForFunction(async()=>(await window.shiban.call('state')).value.settings.chat.memoryRecent==='最近在整理实验');
    await page.locator('#undo-memory').click();
    await page.waitForFunction(async()=>(await window.shiban.call('state')).value.settings.chat.memoryRecent==='');
    await page.locator('[data-settings-tab=appearance]').click();
    assert.equal(await page.locator('[data-capsule-theme=white]').isVisible(),true);
    await page.locator('[data-capsule-theme=white]').click();
    await page.waitForFunction(async()=>(await window.shiban.call('state')).value.settings.capsuleTheme==='white');
    assert.ok((await page.locator('.skin-preview').innerText()).includes('White Default'));
    await page.locator('[data-capsule-theme=black]').click();
    await page.waitForFunction(async()=>(await window.shiban.call('state')).value.settings.capsuleTheme==='black');
    assert.ok((await page.locator('.skin-preview').innerText()).includes('Black Default'));
    await page.locator('.skin-preview').screenshot({path:path.join(__dirname,'../qa/default-black.png'),animations:'disabled'});
    const pet=app.windows().find(w=>w.url().endsWith('pet.html'));
    assert.ok(pet,'desktop capsule exists');
    for(const [theme,isWhite] of [['black-logo',false],['white-logo',true]]){
      await page.locator(`[data-capsule-theme="${theme}"]`).click();
      await page.waitForFunction(async value=>(await window.shiban.call('state')).value.settings.capsuleTheme===value,theme);
      await pet.waitForFunction(value=>document.querySelector('#pet').classList.contains('logo-skin')&&document.querySelector('#pet').classList.contains('white')===value,isWhite);
      assert.equal(await pet.locator('.capsule-logo').isVisible(),true);
      assert.equal(await pet.locator('.capsule-wordmark').isVisible(),false);
    }
    await page.locator('[data-capsule-theme=black]').click();
    await page.locator('[data-settings-tab=data]').click();
    assert.ok((await page.locator('.jot-settings-footer').innerText()).includes('GitHub'));
    assert.equal(await page.locator('#open-github').getAttribute('title'),'打开 github.com/cenzihan/Jot');
    await page.locator('[data-settings-tab=model]').click();
    await page.locator('#profile-new').click();
    await page.locator('[name=profileName]').fill('本地测试');
    await page.locator('[name=profileBase]').fill(modelUrl);
    await page.locator('[name=profileModel]').fill('demo-a');
    await page.locator('[name=profileKey]').fill('test-key');
    await page.locator('#profile-test-edit').click();
    await page.waitForFunction(()=>document.querySelector('#profile-edit-status')?.textContent.includes('连接成功'));
    await page.locator('#profile-save').click();
    await page.waitForFunction(async()=>((await window.shiban.call('state')).value.settings.chat.profiles||[]).some(p=>p.name==='本地测试'));
    const profileState=(await page.evaluate(()=>window.shiban.call('state'))).value.settings.chat;
    assert.equal(profileState.key,undefined);
    assert.equal(profileState.profiles.find(p=>p.name==='本地测试').key,undefined);
    assert.equal(profileState.activeProfileId,profileState.profiles.find(p=>p.name==='本地测试').id);
    await page.locator('#profile-test-edit').click();
    await page.waitForFunction(()=>document.querySelector('#profile-edit-status')?.textContent.includes('连接成功'));
    await page.screenshot({path:path.join(__dirname,'../qa/profiles.png'),animations:'disabled'});
    const qwen=await page.evaluate(()=>window.shiban.call('profile-save',{name:'千问',baseUrl:'https://dashscope.aliyuncs.com/compatible-mode/v1',model:'qwen-plus',format:'openai'}));assert.equal(qwen.ok,true);
    await page.evaluate(async()=>{await refresh();render();});
    await page.waitForFunction(()=>!!document.querySelector('.profile-card img[src*="qwen.svg"]'));
    assert.equal(await page.locator('.profile-card img[src*="qwen.svg"]').evaluate(img=>img.complete&&img.naturalWidth>0),true);
    await page.locator('main').evaluate(el=>el.scrollTop=0);
    await page.screenshot({path:path.join(__dirname,'../qa/profiles.png'),animations:'disabled'});
    await page.locator('.profile-card').filter({hasText:'千问'}).locator('[data-profile-use]').click();
    await page.waitForFunction(async()=>((await window.shiban.call('state')).value.settings.chat.model==='qwen-plus'));
    assert.equal((await page.evaluate(()=>window.shiban.call('state'))).value.settings.chat.hasKey,false);
    assert.deepEqual(errors,[]);
    console.log('PASS: Today/Todo, calendar, chat, profiles, connection test, logo, memory, no page errors');
  }finally{if(app)await app.close();await new Promise(resolve=>modelServer.close(resolve));fs.rmSync(dir,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exitCode=1;});
